### ISSUE TITLE
Paths turn back to dirt (aka Mud) without rain.

### ISSUE THREAD

**Issue by joeldesante** [JoelDesante/RuggedTrails#6]
**Describe the bug**
Grass Paths, when formed are only supposed to turn back into dirt when a player walks over one in the rain. Currently, this happens with or without rain.

**To Reproduce**
1. Make a path
2. Walk over it again (without rain) until it turns into dirt.

**Expected behavior**
It should not revert to dirt unless it is actively raining.

**Additional context**
This bug is rooted in the BlockStepListener class somewhere. I think it is caused by spigot or Minecraft interpreting grass paths as some form of dirt. Though it does have it's own "ID" so that wouldn't make sense.

**Comment by JoelDesante** [comment]
This bug has been mostly resolved.

The only thing that must be solved is how to prevent the player from clipping into mudded dirt... maybe turn into wet farmland?

**Comment by joeldesante** [comment]
This bug has been resolved.

When mudding is enabled (via config), during times of rain, grass paths will turn into Mud (aka Wet Farmland). 

I know that this feature may not be desirable for all, so by default, it is disabled in the config.

It will be implemented in v0.4.0
